---
language: python
python:
  - "3.6"
cache: pip
install:
  - pip install yamllint
script:
  - yamllint -c linter/rules.yml .
notifications:
  slack:
    rooms:
      - libtechnyu:LlugsWft1yLn0vVSO052wfu3#campusmedia
