version: '2.1'
orbs:
  python: circleci/python@2.0.3
jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install yamllint
          command: |
            pip install yamllint
      - run:
          name: Test YAML
          command: |
            yamllint -c linter/rules.yml .
workflows:
  main:
    jobs:
      - test
